version: '3.8'
services:
  client-service:
    build: ./services/client-service
    ports:
      - "8088:8088"
    depends_on:
      - rabbitmq
      - db
  banking-service:
    build: ./services/banking-service
    ports:
      - "8089:8089"
    depends_on:
      - rabbitmq
      - db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microbank
    ports:
      - "5432:5432"