# Default (dev) profile
server:
  port: 8089

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:bankingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---

# Production profile
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  datasource:
    url: jdbc:postgresql://db:5432/microbank
    driver-class-name: org.postgresql.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
  address: 0.0.0.0

---

# Common configuration (applies to all profiles)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.microbank: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

feign:
  client:
    config:
      client-service:
        url: http://client-service:8088
